################################################################################
# training parameters
################################################################################
train:
  pipeline: "res"       #  "res" "fid" "hard"
  act: "Hardswish"      #  "SiLU" "Hardswish" "LeakyReLU"
  loss: "xentropy"      #   must be either xentropy or iou
  aux_loss: True
  lamda: 1.0
  scheduler: "consine"  # "consine" or "decay"
  max_epochs: 30
  consine:
    min_lr: 0.0001
    max_lr: 0.01
    first_cycle: 30
    cycle: 1
    wup_epochs: 1
    gamma: 1.0
  decay:
    lr: 0.01
    wup_epochs: 1        # warmup during first XX epochs (can be float)
    lr_decay: 0.99       # learning rate decay per epoch after initial cycle (from min lr)
  momentum: 0.9          # sgd momentum
  w_decay: 0.0001        # weight decay
  batch_size: 6          # batch size
  report_batch: 100      # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard   Must false since not check the api
  save_scans:  False     # False doesn't save anything, True saves som
  show_scans: True       # show scans during training
  save_batch: 50
  workers: 6             # number of threads to get data

################################################################################
# postproc parameters
################################################################################
post:
  KNN:
    use: True # This parameter default is false
#     params:
#       knn: 5
#       search: 5
#       sigma: 1.0
#       cutoff: 1.0
    params:
      knn: 7
      search: 7
      sigma: 1.0
      cutoff: 2.0

################################################################################
# dataset (to find parser)
################################################################################
dataset:
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25
    img_prop:
      width: 1024
      height: 64
    img_means: #range,x,y,z,signal
      - 11.71279
      - -0.1023471
      - 0.4952
      - -1.0545
      - 0.2877
    img_stds: #range,x,y,z,signal
      - 10.24
      - 12.295865
      - 9.4287
      - 0.8643
      - 0.1450
#     img_means: #range,x,y,z,signal
#       - 11.71279
#       - -0.1023471
#       - 0.4952
#       - -1.0545
#       - 0.2877  
#       - 0.0035755096
#       - 0.39993516 
#       - -0.0023758996
#     img_stds: #range,x,y,z,signal
#       - 10.24
#       - 12.295865
#       - 9.4287
#       - 0.8643
#       - 0.1450   
#       - 0.44721574
#       - 0.568866
#       - 0.46991134